### ISSUE TITLE
Problemas de acceso

### ISSUE THREAD

**Issue by Dikakus** [ogarcia/ultrasonic#1]
Hola Óscar. He instalado tu aplicación en un Sony Xperia Z2 con Lollipop 5.1.1. He configurado el servidor pero cuando intento acceder a la biblioteca de música se lanza el error:

"org.subsonic.restapi.Artist.setAverageRating(LJava/lang/Double;)V"

Después he intentado comprobar la conexión desde la configuración del servidor y el error es:

"Fallo de conexión. org.subsonic.restapi.License.setLicenseExpires(Ljavax/xml/datatype/XMLGregorianCAlendar;)V"

El servidor subsonic es la versión 5.3.beta2 del 22/08/2015.

¿Sabes si es problema de mi móvil? ¿De la versión de subsonic?

Muchas gracias de antemano.

Un saludo,
Diego.

**Comment by ogarcia** [comment]
Buenas Diego,

No he tenido tiempo aún de probar con la beta de la 5.3. Posiblemente venga por ahí el problema porque con la estable no da errores.

Esta semana y la que viene estoy un poco desconectado del mundo. Pero si puedo (y me dejan) hago pruebas y te cuento.

¿Podrías comprobar tu con la estable en una instalación paralela? Así vamos descartando.

Saludos.

**Comment by ogarcia** [comment]
He realizado comprobaciones con la beta y no tiene problemas, el cliente funciona perfectamente. ¿Has revisado la configuración?
Por otro lado, para poder acceder al Subsonic vía API, es decir, usando una aplicación, tienes que tener la versión Premium que es de lo que parece quejarse el error que me comentas.
