### ISSUE TITLE
Cache folder

### ISSUE THREAD

**Issue by davidgfnet** [ogarcia/ultrasonic#2]
It would be great to use android's native cache for music cache. What d you think?
Are you gonna mantain and improve Ultrasonic? Im interested since I use it quite a bit. I created a simple python server (check my repos) and I would be really interested in improving and extending the protocol. 
Gracias!

**Comment by ogarcia** [comment]
Hi @davidgfnet,

Sorry, but I not have time to write new code or upgrade Ultrasonic. :cry:

This does not mean that you can not improve it. You can send a PR and I can merge it, update package in Google Play and add you as collaborator.

Greetings.
