### ISSUE TITLE
Many thanks

### ISSUE THREAD

**Issue by biconou** [ogarcia/ultrasonic#3]
Hi, 

Many thanks for the rebirth on Ultrasonic. This wonderfull app had disappeared but now it is again available.
I use this app daily and I Would like to contribute to some evolutions. I am a java developer but completely newbie on android. 
However I started to fork it, import it in android studio, experienced debug on my phone and I even commited my first minor modification.

**Comment by ogarcia** [comment]
@biconou great!

You can send a PR when you want without problems. :wink:
