### ISSUE TITLE
How to create a playlist of all songs 

### ISSUE THREAD

**Issue by even0306** [ogarcia/ultrasonic#589]
我连接在自建音乐服务器上，上面的所有歌曲都是我喜欢听的，我想要随机播放所有歌曲，但目前只能随机25首歌曲播放，希望能改善一下，或者能告诉我如何才能做到随机播放所有歌曲。谢谢

**Comment by nitehu** [comment]
English only please. If you're not good with that please use google translate at least.

> I am connected to a self-built music server. All the songs above are what I like to listen to. I want to play all the songs randomly, but currently only 25 songs can be played randomly. I hope it can be improved or can tell me how to do it. To shuffle all songs. thanks 

Would you please give the server you're using? Creating a playlist has nothing to do with Ultrasonic, your server must support that. Ultrasonic can shuffle the songs for you on a playlist of any size, so they can be played in a random order.

I use [Ampache](https://ampache.org/) as my server, it supports ordinary and smart playlists of any size, even with a random order. I usually load a random playlist of a few thousand tracks into Ultrasonic and use it as my own radio station.

**Comment by even0306** [comment]
> 请只说英文。如果您对此不满意，请至少使用谷歌翻译。
> 
> > 我连接到自建音乐服务器。以上所有歌曲都是我喜欢听的。我想随机播放所有歌曲，但目前只能随机播放25首歌曲。我希望它可以改进或可以告诉我如何去做。随机播放所有歌曲。谢谢
> 
> 你能提供你正在使用的服务器吗？创建播放列表与 Ultrasonic 无关，您的服务器必须支持。Ultrasonic 可以在任意大小的播放列表中为您随机播放歌曲，因此它们可以按随机顺序播放。
> 
> 我使用[Ampache](https://ampache.org/)作为我的服务器，它支持任何大小的普通和智能播放列表，即使是随机顺序。我通常将几千首曲目的随机播放列表加载到 Ultrasonic 中，并将其用作我自己的广播电台。

I use the music plugin of nextcloud, how do I create a playlist

**Comment by nitehu** [comment]
We don't really know all the server implementations, but I'm sure the nextcloud users can help you here:
[https://help.nextcloud.com/](https://help.nextcloud.com/)
Also you may contact the nextcloud / owncloud music app developers here:
[https://github.com/owncloud/music](https://github.com/owncloud/music)

**Comment by Maxmystere** [comment]
If you are limited with the 25 songs when using random, then you can just increase the size of the request in ultrasonic settings -> search parameters -> maximum titles (or something like that I don't have English app)

I hope it was what you were requesting

**Comment by even0306** [comment]
I created a list of m3u8 songs in nextcloud's music and then ultrasacred successfully synced it. Problem solved. Thanks
