### ISSUE TITLE
Media Keys support 

### ISSUE THREAD

**Issue by adamschoenemann** [ogarcia/ultrasonic#6]
First of all, thank you for this wonderful little app. 
I recently purchased some headphones with a single button media key - 1 press for play / pause,  two presses for next, three for previous. However, Ultrasonic will only register the single button press! A different media player does register the other functions, so it should not be a problem with my phone :-)

**Comment by ogarcia** [comment]
I do several tests with some BT devices and all of them works well cause the media keys depends of Android system.

I think that your device are not using the standard method. :disappointed:

**Comment by adamschoenemann** [comment]
Hmm OK, thanks for the effort. I'll try to investigate more - maybe my headphones simply do not work properly.
