### ISSUE TITLE
targetSdkVersion must be 30 or higher

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/ultrasonic#613]
To upload new releases after november, 1 we must set `targetSdkVersion` to 30 or higher

**Comment by nitehu** [comment]
Regarding this, I'm mostly afraid of the [storage related changes](https://developer.android.com/training/data-storage#scoped-storage). Ultrasonic probably will work well if the music cache is inside its own directory, but we must refactor a few thing if we want to allow to store media files anywhere else on the device...

**Comment by tzugen** [comment]
https://developer.android.com/about/versions/11/privacy/storage

**Comment by tzugen** [comment]
We should redesign PermissionUtil. The Dexter framework that we are currently using is not being developed anymore

**Comment by tzugen** [comment]
After reading a bit I guess the intended idea for our use case (storing Media items) is to use the MediaStore.
We had a broken MediaStore implementation, where we tried to custom set the URI of the media item. That never worked. As far as I understand, we should now just hand the media item to the MediaStore API, and let it take care of storing the file.

But I can't figure out if we can migrate existing data. If we target API 29, we can use requestLegacyStorageAccess(), but that function doesn't do anything in API 30, so maybe we are actually too late to create a migration code?

**Comment by tzugen** [comment]
https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage

**Comment by nitehu** [comment]
If I understand correctly we shouldn't migrate anything as most files of Ultrasonic are in its own directory except the music cache, and we don't want to move that (it can be fairly big, and the user may want to find their music where they left it :)).
The bigger problem seems to be for me that how can we access the old cache / music folder with the MediaStore API, request permissions for it, etc.

**Comment by ogarcia** [comment]
I don't worry about adding a breaking change. We can add a **BIG FAT WARNING** (in changelog and Play Store update notes) avoiding that the old cache is inaccessible and that the user must start caching again. Note that cache definition says that "it's data that can be deleted".

**Comment by tzugen** [comment]
I figured out we don't need a warning :)

We can add the `preserveLegacyExternalStorage` flag to the manifest.
This makes that existing installs can still access their old storage locations, but when the app is newly installed only scoped storage is available.

Therefore I would suggest following:

- [x] Change API to 30 and add `preserveLegacyExternalStorage` flag
- [ ] On launch of the app, check if it is the first launch of an existing install on API 30.
- [ ] If yes, open a dialog which explains the situation
- [ ] Users can opt to migrate their cache, or just keep it where it is
- [x] Remove ability to change the cache location in the Preference screen
- [ ] Add button to migrate cache location (visible only for old users with external cache)
- [ ] Hide cache location setting completely for new users

I will tick the things done in the PR. I am happy if other people work on the PR as well!

**Comment by nitehu** [comment]
I still think that Ultrasonic should be able to access a media directory outside of the scoped storage, and moving the cache is not a (final) solution. Users seem to need this feature, there are several issue reports and bad ratings if it doesn't work correctly. Also it seems other media players (e.g. Poweramp) have found a solution to this too.

**Comment by tzugen** [comment]
I agree that it would be preferable to keep this feature.

There is a new Permission MANAGE EXTERNAL STORAGE, but according to play store policies only certain apps (like backup tools are allowed to request it).

Can you find out more how Poweramp does it?

**Comment by nitehu** [comment]
I'm pretty sure it uses the [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory). At least the process to select your media folders is the following:
- At the start it doesn't have any permissions
- You can add a folder by pressing an "enable" button, which shows a system file picker, where a folder can be selected and permission can be added to that single folder (however, this single folder can be the storage root on my phone, and selecting it will give access to my whole storage)
- After the permission is added, you can browse the folder's contents in Poweramp

After this procedure it seems read/write access works properly. I think it uses the [DocumentsProvider](https://developer.android.com/reference/android/provider/DocumentsProvider) instead of the File API.

**Comment by tzugen** [comment]
Ah perfect, the first link seems to describe pretty well what we need to do.

**Comment by tzugen** [comment]
I have implemented the basic stuff from the article in the PR, maybe you can have a look at it when you have time.
