### ISSUE TITLE
Ultrasonic Media List is Empty After Airsonic Server Crash

### ISSUE THREAD

**Issue by iUnknwn** [ogarcia/ultrasonic#614]
## Problem description

After a power outage crashed my Airsonic server, I rebooted the server, and Airsonic appeared to be working normally - I could access the web interface, and I was able to play music without issue. 

However, in Ultrasonic, the album list was blank. The artist list was still populated, but clicking any artist would show an empty list. All lists were either blank, or had items that were empty (Random, for example, would show a list or albums but, like artists, clicking any individual album would show a blank list).

Rebooting the server not resolve the problem, nor did removing and re-adding the server in Ultrasonic. 

Instructing Airsonic to rescan the media library seemed to resolve the issue, with Ultrasonic's media library re-appearing after the update.

### Steps to reproduce

I'm not certain how to reproduce, but it is possible the crash resulted in the server losing its NFS mount with the music, briefly. So it is possible there was some period in which Airsonic was up but there were no files (though I can't be certain of that, since when I loaded Airsonic in my browser it was working).

## System information

 * **Ultrasonic version**: Ultrasonic is 2.23.1 (from Google Play)
 * **Android version**: Android Version 11 with October 2021 patch.
 * **Device info**: Pixel 3a
 * **Airsonic version**: 10.6.2-RELEASE

**Comment by nitehu** [comment]
Thank you for reporting this, however I'm not sure what would be the expected behavior of Ultrasonic in this case. 
As I understand, Ultrasonic now works for you normally with your Airsonic server after the library rescan? 
This very much looks like it was a server-side problem, as you've mentioned.
Do you have the Airsonic server logs from the incident? There we could check and make sure if it was a client or a server problem.

**Comment by iUnknwn** [comment]
I agree - it's not clear if the problem is with Airsonic or with Ultrasonic - the Airsonic web interface was working after the crash, so that's why I suspected Ultrasonic, but given it was resolved by a library rescan... I'm not sure.

Unfortunately, it doesn't look like the server logs were retained from the crash. 

If you'd like, we can close this, and if this happens again, I'll have the server save logs and I can re-open. Is there a specific log you need, or is the Airsonic server output sufficient (I'm running Airsonic via the LinuxServer Docker image - so I can give you the container output, but do you need anything else)?

**Comment by nitehu** [comment]
Yes, I think that would be the best - I don't know where to start finding the problem without the logs, if it is in Ultrasonic at all.
The console output for Airsonic should be enough, I think that's also the container output in case of docker. Also, if a similar problem happens again, the debug log (or logcat) from Ultrasonic could come in handy.
Please reopen this if the problem returns or you have any more information.
