### ISSUE TITLE
Play back all offline tracks

### ISSUE THREAD

**Issue by paroj** [ogarcia/ultrasonic#624]
## Problem description
Is there a way to play back all & shuffle downloaded tracks?

### Steps to reproduce
Currently, if I select the Offline Server, I can browse the downloaded songs by Media-Library or by Playlist, but there is no apparent way to add all of them to the playback queue and shuffle them.
Whereas, there is the "Title > Shuffle" option on the main-page, when connected to the server.

## System information

 * **Ultrasonic version**: 2.23.1

**Comment by paroj** [comment]
ok, just tried 2.24 from f-droid on a different device, where this is implemented. I guess I will have to wait until it hits the play store, as otherwise I would have to re-download my library again.

**Comment by Maxmystere** [comment]
Yes it was implemented [here](https://github.com/ultrasonic/ultrasonic/pull/559)
