### ISSUE TITLE
Evaluate recent list

### ISSUE THREAD

**Issue by tzugen** [ogarcia/ultrasonic#644]
We used to update the File modification date in certain cases, to ensure that the CacheCleaner would remove only the most stale files. Evaluate if this is really necessary, and if so , how to do this with SAF

**Comment by ogarcia** [comment]
@tzugen How is this? Please tag this issue and add to any milestone (or backlog). Or close it if it is done :+1:

**Comment by tzugen** [comment]
No its still relevant

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/644
