### ISSUE TITLE
Improve database migrations

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/ultrasonic#662]
Now in [database migrations][1] we have all upgrades done but downgrades not. This cause that if an user downgrades the application for any reason, they will have an error and Ultrasonic will not run.

We need to add all database downgrade migrations.

[1]: ../tree/3588bb93805679dffe6e2a7a728ed6f8e3edea8f/ultrasonic/src/main/kotlin/org/moire/ultrasonic/data/AppDatabase.kt

**Comment by ogarcia** [comment]
@tzugen and @nitehu we have a little problem with this. I can tag now master as 2.24.1 to perform an intermediate release that provides full database migrations. But we have a problem with the fucking Google Play and the fucking API level 30. (I can upload this release because is using API 29).

We have two options.
1. Tag the master to create the intermediate version for F-Droid (and GitHub) and if a Google Play user leaves the beta will have a crash (and need full reinstall or delete all aplication data).
2. Make changes in develop to don't change database version, for example we can release a 3.0.0 that stores de server color in a shared preference (or that simply pick default color for all servers) and next upgrade to 3.1.0 with the color selector.

Tell me what do you prefer.

**Comment by nitehu** [comment]
Sorry, I'll be afk for a few more days... if it is easier just roll back
the server color changes... we can add them back when the dust settles. Or
if that's too much work, just hide the color selector and use a fix color
for an intermediate version.

**Comment by ogarcia** [comment]
Yes, I also prefer to hide color selector and use a fix color.

As we all are AFK from holidays, I propose that we put this (and #650) on hold and get back to it in a few days.

**Comment by tzugen** [comment]
Should we do it now?
1. Merge #660
2. Create a patch to disable the custom color stuff
3. Release it!

**Comment by nitehu** [comment]
I'm back now too!
1. #660 looks ok to me too
2. so this would be a patch which uses DB version 3, without the color column, and all the UI features removed where the color would be used, if I understand it correctly?

**Comment by ogarcia** [comment]
Yes. The path is:

1. Merge #660
2. Change database version to 3 (keeping all migrations, of course)
3. Do a patch to hide color selector and simply set a default color for servers, it can be the already chosen one.
4. Release it as 3.0.0

Next in 3.1.0 we can remove the patch and change database version to 4.

And from here on, we would always have to remember to launch patches with the DB migrations before they occur so that in case of downgrading the user has no problems.

**Comment by tzugen** [comment]
Nice thing, with Room 2.4.0, there will be support for automagic migrations..

**Comment by tzugen** [comment]
Hi, I have pushed a branch #667 which deactivates the custom color and sets the DB to version 3. 
If it works for you I think we can release 2.24.1 from it.

No need to merge the PR into develop!

**Comment by tzugen** [comment]
@ogarcia @nitehu

**Comment by ogarcia** [comment]
@tzugen I think that is better merge it into develop to don't leave branches dangling and after perform release do the rollback.

I'm AFK until monday but if I can I will do the release before.

**Comment by ogarcia** [comment]
Release done! I think that now we can perform rollback of #667 and close this ticket

**Comment by tzugen** [comment]
#678 was merged
