### ISSUE TITLE
Weird behaviour and system crash

### ISSUE THREAD

**Issue by KingDuckZ** [ogarcia/ultrasonic#664]
## Problem description

Disclaimer: I don't know if this is an issue with this app or with the OS. I don't see this issue on a different phone running stock Android.

I recently noticed a stability issue happening when I play back ogg music. At first songs play fine (mostly the first one), then the app starts skipping songs in the playlist after a brief pause on each song, as if it's unable to play it. Sometimes the whole playlist is unplayable and sometimes it resumes playback from one of the following songs.
If I click back on an already played song (for example the first), the app skips it and it's unable to play it back again even if it just worked fine. It mostly seems to work on freshly downloaded songs only, but it's hard to tell because the behaviour is really erratic.

Clicking on "unplayable" songs enough times leads to the app freezing, the UI restarting or even the phone crashing entirely and producing a core dump.

I don't know since when this issue started because I had set my music server (Navidrome) to transcode to opus, and playback is mostly fine there. Yesterday I removed the transcoding rule and now I'm just streaming the original ogg files, which caused the problem I described above. Switching back to opus seems to mitigate this issue.

### Steps to reproduce

1. get a Navidrome server with some ogg files on it
2. make sure it's got no transcoding setting for the Ultrasonic player
3. from Ultrasonic pick an album and play it
4. wait for the first song to finish
5. alternative 1: click on the progress bar to skip part of the song
6. alternative 2: while the first song is playing click on the second one in the playlist
7. the second song won't play, most of the times the third will, but just once, then the fifth and so on (this is the overall behaviour I observed, but it's not very consistent)

## System information

 * **Ultrasonic version**: *2.24.0*
 * **Android version**: *LineageOS 18.1 24th Dec 2021*
 * **Device info**: *Asus Zenfone 8*

## Additional notes

I don't know if this is a problem with some systems components provided by the OS.
From my laptop everything works fine (browser and Strawberry player) and I don't see any error on the Navidrome side.

After the problem starts occurring, even if the system doesn't crash I still have to reboot it as sound is completely gone. For example youtube videos in Newpipe will have no sound, and sometimes play in a laggy/slow way.

Sometimes closing Ultrasonic becomes impossible without a full reboot, ie I click on the `X` button in the play widget from the drop down system menu and nothing happens.

**Comment by tzugen** [comment]
Does it still happen?

**Comment by tzugen** [comment]
If yes, maybe provide a debug user login to be able to reproduce it.

**Comment by glu8716** [comment]
I don't know if this is related, but I'm getting a similar issue with opus transcoding from Navidrome (it doesn't happen with mp3 transcoding). 
When I start to play a playlist (usually using random) the first three songs are downloaded multiple times and multiple .oga files are created in the app's cache folder. If you skip to the next track it stops downloading those files multiple times, but then music doesn't play anymore.
I'm attaching the log here.
[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/8328220/ultrasonic.1.log)

**Comment by tzugen** [comment]
@glu8716 Can you try with the beta version?
