### ISSUE TITLE
Release 3.0.0 apk is broken

### ISSUE THREAD

**Issue by hmueller01** [ogarcia/ultrasonic#668]
## Problem description

apk of [release 3.0.0](https://github.com/ultrasonic/ultrasonic/releases/tag/3.0.0) can not be installed. Installer says something like it is not valid. Is it only on my Andoid 12 phone?

### Steps to reproduce

Dowload and install.

## System information

 * **Ultrasonic version**: *3.0.0*
 * **Android version**: *Android 12*
 * **Device info**: *Google Pixel 6*

**Comment by ogarcia** [comment]
I can't reproduce. I can install it without problems.

The already installed version is the same (GitHub version) or is from other source? Take note that all three versions (Google Play, F-Droid and the APKs) are not compatible (not signed by the same key). You must uninstall one to install the other, which will delete all your data.

**Comment by hmueller01** [comment]
I know. I uninstalled the f-droid version before. Cloning the repo and rebuilding with Android Studio worked at the end. Have you downloaded the apk from here again? [Apk Analyzer](https://play.google.com/store/apps/details?id=sk.styk.martin.apkanalyzer&hl=de&gl=US) also complained about the apk you provided (loading failed). I downloaded twice to ensure download errors.


I download with my PC and the Pixel. The versions are identical.
```
> crc32 ultrasonic-3.0.0.apk 
4e1ba924

> shasum ultrasonic-3.0.0.apk 
3b3749ba3e8c867491c9e23293dd920010d1551d  ultrasonic-3.0.0.apk
```

**Comment by ogarcia** [comment]
> Have you downloaded the apk from here again?

Yes because the APK is builded in our CI system.

**Comment by punk3r70** [comment]
I have the same issue. Clean install.

Ultrasonic version: 3.0.0
Android version: Android 12
Device info: Samsung Galaxy S21

**Comment by hmueller01** [comment]
Just tried on an old Android 9 phone and there the APK works. Tried again on an Android 12 (API 31) emulator using drag and drop shows this error message
<img width="540" alt="Bildschirmfoto 2022-01-18 um 16 53 36" src="https://user-images.githubusercontent.com/11197280/149972286-01559648-a9a1-431a-81a3-ee8cbcf45232.png">

Uploading and installing from the file manager shows the same error as on my Pixel 6
<img width="337" alt="Bildschirmfoto 2022-01-18 um 17 00 03" src="https://user-images.githubusercontent.com/11197280/149973073-1ef06c51-074c-48cd-bdb3-a3f61070cb40.png">

**Comment by ogarcia** [comment]
@hmueller01 @punk3r70 try again now that I change the sign method and I think that it must work now

**Comment by hmueller01** [comment]
Tx, this works for me. Apk Analyzer as well as Pixel 6 accept this APK.

**Comment by punk3r70** [comment]
Works fine! 😊
________________________________
Från: Óscar García Amor ***@***.***>
Sänt: onsdag 19 januari 2022 10:09
Till: ultrasonic/ultrasonic
Kopia: punk3r70; Mention 
Ämne: Re: [ultrasonic/ultrasonic] Release 3.0.0 apk is broken (Issue #668)

@hmueller01 @punk3r70 try again now that I change the sign method and I think that it must work now
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
