### ISSUE TITLE
Now playing list should be able to distinguish duplicate items

### ISSUE THREAD

**Issue by nitehu** [ogarcia/ultrasonic#680]
## Problem description

It seems currently the now playing list only ditinguishes items by their song id, and not their place in the list. This causes problems like this:

![Screenshot 2022-02-05 130236](https://user-images.githubusercontent.com/55684536/152641973-24de441e-017b-4946-87e8-9cac1067292c.jpg)

When there is the same song two or more times on the list, all instances will show the same state (e.g. playing).
The removal of the song works strange too, if you delete a song, always the first instance will be deleted, and not the one you swiped away.

### Steps to reproduce

- Add the same song to the playlist at least twice
- Play the song: all instances are playing
- Delete the song: always the first instance is deleted

**Comment by tzugen** [comment]
Playlist is managed in downloader.kt
In trackviewholder we have this logic:

````
        rxSubscription = RxBus.playerStateObservable.subscribe {
            setPlayIcon(it.track == downloadFile)
        }
````

**Comment by tzugen** [comment]
Simple check if the displayed track is equal the currentPlaying track

**Comment by tzugen** [comment]
Maybe we should extend  `RxBus.playerStatePublisher.onNext(RxBus.StateWithTrack(playerState, track))` to include current tracknumber? And then we can compare if it is the right istance? @nitehu

**Comment by nitehu** [comment]
> include current tracknumber? And then we can compare if it is the right istance?

Ugh, this opens up a way bigger refactor than I expected... the DownloadFile instance is used everywhere instead of the track number. Also, PlayerStatePublisher replays the last event for the new subscribers, which is bad because the track number can change without the player state (when an item is moved in the playlist).
I'll try to find a simple solution which isn't too hacky...

**Comment by nitehu** [comment]
I've just noticed, playlist handling is so broken a duplicate song will force it to play in an endless loop between the two song instances. This is because the next() function determines which song is playing currently by searching it in the playlist, and will always find the first one :(
So the playlist handling must be refactored to track and use the playing song index separately.

Edit: or maybe a separate DownloadFile instance could be created for all items on the playlist instead of using the cached one. But I'm not sure if this breaks something somewhere else...
Edit2: Yep this breaks the status of the DownloadFile instances which point to the same file, so this wasn't such a good idea.

**Comment by tzugen** [comment]
Let's focus our efforts on switching to a more modern base for our playback and let a library with much more testing take care of all these details....

(see my discussion #724)

**Comment by tzugen** [comment]
Confirmed fixed with #726

**Comment by hmueller01** [comment]
#726 mostly fixes this. The only thing I still found is that the playback list play icon stays at the first double entry if the second song is played and no other song is in between. Pressing Pause/Play fixes this.

**Comment by tzugen** [comment]
I have fixed this in a branch, but I don't want to push it now, but rather keep the PR stable for now.
