### ISSUE TITLE
Rewrite the about and remove the webview

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/ultrasonic#683]
Recently our _dear_ friends at Google block the latest update (3.0.1) because they don't like that there is a donate button in the about section and send this:
![org moire ultrasonic-InAppExperience-46](https://user-images.githubusercontent.com/572924/153402410-a7632dca-7baf-4ab2-8424-96947b7a490b.png)

But wait, they have another hilarious argument for blocking the app and it's caused by this flow (I am not even going to evaluate it):
![org moire ultrasonic-InAppExperience-327](https://user-images.githubusercontent.com/572924/153402602-43f7d1c5-bbc1-4da6-a8bf-8d3ef822133d.png)

I am using all the donations that have been received to pay for the moire.org domain and they are not enough to pay for anything else. With this I do not mean that I want more money to be donated, on the contrary, the domain is paid until next year and there are funds to pay at least one more year.

Side note for @tzugen @nitehu and rest of contributors. If at any time we need to set up a VPS for testing purposes, these funds can be used.

At this point we have two options.

- The first is what I propose in https://github.com/ultrasonic/ultrasonic/discussions/682 (which may be too radical, but if we all agree, I have nothing more to add).
- The second one is remove the about text and webview and set a simple fixed about window that links to https://ultrasonic.github.io/ and here (https://github.com/ultrasonic/ultrasonic) and add the donation button in Github.

**Comment by nitehu** [comment]
There is also a third option: maybe we can set up to build a separate version for FDroid and the Play Store (it may even use the same codebase, with some conditional compilig (I'm not yet sure how much is that supported in Android)). 

Anyways, this was a really sh!t move from google, I can't understand why would they want a piece of your donations. But if we have a separate play store version, maybe we can also add a donate button through the play store...

**Comment by ogarcia** [comment]
I think that maintain two versions is going to be a lot of work. Maybe the best thing to do is not to be so radical and go for the second option. Remove the current about and add a simple about window that list the contributors and one or two links to here that opens the user browser instead of internal app navigation.
