### ISSUE TITLE
Android Auto regression since 3.x.x

### ISSUE THREAD

**Issue by Break-Off** [ogarcia/ultrasonic#687]
## Problem description

Hello. Since updating to 3.x.x, I've been having problems with Android Auto and Ultrasonic. Sometimes, the application refuses to work with Android Auto. The issue happens inconsistently, but sooner or latter it happens again. The only workaround is going to the app settings, deleting all application data, and start over, but it comes back after a while.

### Steps to reproduce

1. Update to 3.x.x.
2. Connect a smartphone with Ultrasonic to a car with an infotainment system that it's Android Auto-capable.
3. Ultrasonic refuses to work with Android Auto. Only workaround is deleting app data, but it comes back.

## System information

 * **Ultrasonic version**: *3.0.1 (F-Droid version)*
 * **Android version**: *Android 11, official Samsung ROM (rooted)*
 * **Device info**: *Samsung Galaxy A51 5G*

## Additional notes

Also, A2DP has stopped working with another car, showing "Not Provided" as music information in the infotainment display. I've been unable to document this latter issue, but it seems related since they both happened at the same time.

The music player controls shown as a notification also disappeared, but I can't determine if it's related.

Please advise on how to debug this issue.

### Before 3.x.x (2.24.0)
![20220215_135934](https://user-images.githubusercontent.com/5843433/154072140-53a6c046-1cd5-4951-9563-3bc3580c75e7.jpg)

### After 3.x.x (3.0.1)
![20220211_191942](https://user-images.githubusercontent.com/5843433/154072127-93411150-197a-4abc-8db5-f270441f3c94.jpg)

**Comment by nitehu** [comment]
I'll try to reproduce this in an emulator.
Meanwhile, could you please check if there are any exceptions in the Ultrasonic folder, in the debug log or in logcat?

**Comment by Maxmystere** [comment]
While it exist there is this app that behave like an android auto screen that could help with testing
https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead.phonescreen

**Comment by Break-Off** [comment]
> I'll try to reproduce this in an emulator. Meanwhile, could you please check if there are any exceptions in the Ultrasonic folder, in the debug log or in logcat?

Thanks for looking into the issue. Here is a debug log generated by Ultrasonic by checking the "Write debug log to file" option:
```
15:39:41.157: I SettingsFragment Enabled debug logging to file 
15:39:50.452: I AutoMediaBrowserService AutoMediaBrowserService onCreate finished 
15:39:50.512: D AutoMediaBrowserService AutoMediaBrowserService onGetRoot called. clientPackageName: com.google.android.projection.gearhead; clientUid: 10236 
15:39:50.537: D AutoMediaBrowserService AutoMediaBrowserService onLoadChildren called. ParentId: MEDIA_ROOT_ID 
15:39:50.538: D AutoMediaBrowserService AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService... 
15:39:50.560: I AutoMediaBrowserService AutoMediaBrowserService onDestroy finished 
15:39:52.554: I AutoMediaBrowserService AutoMediaBrowserService onCreate finished 
15:39:52.559: D AutoMediaBrowserService AutoMediaBrowserService onGetRoot called. clientPackageName: com.google.android.projection.gearhead; clientUid: 10236 
15:39:52.564: D AutoMediaBrowserService AutoMediaBrowserService onLoadChildren called. ParentId: MEDIA_ROOT_ID 
15:39:52.577: I AutoMediaBrowserService AutoMediaBrowserService onDestroy finished 
15:39:52.653: D AutoMediaBrowserService AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService... 
15:39:56.579: I AutoMediaBrowserService AutoMediaBrowserService onCreate finished 
15:39:56.583: D AutoMediaBrowserService AutoMediaBrowserService onGetRoot called. clientPackageName: com.google.android.projection.gearhead; clientUid: 10236 
15:39:56.587: D AutoMediaBrowserService AutoMediaBrowserService onLoadChildren called. ParentId: MEDIA_ROOT_ID 
15:39:56.608: I AutoMediaBrowserService AutoMediaBrowserService onDestroy finished 
15:39:56.679: D AutoMediaBrowserService AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService... 
15:39:56.891: D BluetoothIntentReceiver A2DP State: -1; Action: android.bluetooth.device.action.ACL_CONNECTED; Device: CAR MULTIMEDIA; Address: 74:D7:CA:92:5C:26 
15:40:04.341: D BluetoothIntentReceiver A2DP State: 1; Action: android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED; Device: CAR MULTIMEDIA; Address: 74:D7:CA:92:5C:26 
15:40:04.610: I AutoMediaBrowserService AutoMediaBrowserService onCreate finished 
15:40:04.614: D AutoMediaBrowserService AutoMediaBrowserService onGetRoot called. clientPackageName: com.google.android.projection.gearhead; clientUid: 10236 
15:40:04.618: D AutoMediaBrowserService AutoMediaBrowserService onLoadChildren called. ParentId: MEDIA_ROOT_ID 
15:40:04.643: I AutoMediaBrowserService AutoMediaBrowserService onDestroy finished 
15:40:04.695: D BluetoothIntentReceiver A2DP State: 0; Action: android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED; Device: CAR MULTIMEDIA; Address: 74:D7:CA:92:5C:26 
15:40:04.696: I BluetoothIntentReceiver Disconnected from Bluetooth device CAR MULTIMEDIA address 74:D7:CA:92:5C:26, requesting pause. 
15:40:04.700: I UltrasonicIntentReceiver Received Ultrasonic Intent: org.moire.ultrasonic.CMD_PAUSE 
15:40:04.703: I MediaPlayerLifecycleSupport Received intent: org.moire.ultrasonic.CMD_PAUSE 
15:40:04.711: D AutoMediaBrowserService AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService... 
15:40:20.642: I AutoMediaBrowserService AutoMediaBrowserService onCreate finished 
15:40:20.647: D AutoMediaBrowserService AutoMediaBrowserService onGetRoot called. clientPackageName: com.google.android.projection.gearhead; clientUid: 10236 
15:40:20.653: D AutoMediaBrowserService AutoMediaBrowserService onLoadChildren called. ParentId: MEDIA_ROOT_ID 
15:40:20.697: I AutoMediaBrowserService AutoMediaBrowserService onDestroy finished 
15:40:20.743: D AutoMediaBrowserService AutoMediaBrowserService starting lifecycleSupport and MediaPlayerService... 
```
I've tried generating a debug log without Bluetooth, but Android Auto turns it on automatically. Let me know if there's another way to debug.

**Comment by ParadingLunatic** [comment]
Just had this issue as well.  Looks like the version on the Google Play Store was upgraded to 3.1.1.  So for now, I uninstalled and sideloaded 2.24.0.

**Comment by cfredericksen** [comment]
> Just had this issue as well. Looks like the version on the Google Play Store was upgraded to 3.1.1. So for now, I uninstalled and sideloaded 2.24.0.

How do you sideload android auto apps and have them show up in android auto? All of the instructions that I have seen are convoluted.

**Comment by ParadingLunatic** [comment]
You have to enable developer options for android auto.  https://techbriefly.com/2021/01/08/how-to-activate-developer-options-in-android-auto/

Then there's a setting you have to change in developer options.  I can't recall off the top of my head what it is though.

**Comment by cfredericksen** [comment]
I forgot the part where you check the 'unknown sources' box. Thanks!

**Comment by tzugen** [comment]
Closing for #756
