### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by fiskhandlarn** [ogarcia/ultrasonic#688]
## Problem description

I'm getting "Connection failure" as of latest version (3.1.0). I haven't changed any of the settings, I just installed the v3.1.0 apk over the previous version.

### Steps to reproduce

Se above.

## System information

 * **Ultrasonic version**: 3.1.0
 * **Android version**: 11
 * **Device info**: Samsung Z Flip3 5G

**Comment by nitehu** [comment]
Please check your server settings, did they change? There were some related db changes, and maybe there was a bug in them.
Can you add a new server and see if that helps?

**Comment by fiskhandlarn** [comment]
@nitehu Nothing has changed on the server. I played songs from the server yesterday evening with v3.0.1 (or if it was 3.0.0). The only thing that has changed is upgrading Ultrasonic to 3.1.0.

> Can you add a new server and see if that helps?

I only have one server.
I just tried with http://demo.subsonic.org/index.view though (username "guest2", password "guest") and get the same error.

**Comment by nitehu** [comment]
Thanks!
Could you please also check if there is an exception file in the Ultrasonic folder, in the debug log (it can be enabled from the settings) or in logcat?

**Comment by fiskhandlarn** [comment]
@nitehu No exception file, but I enabled the log file:

```log
14:25:30.393: I Storage StorageFile caches were reset 
14:25:34.233: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
14:25:34.234: D ActiveServerProvider Cache is invalidated 
14:25:34.236: D ServerSettingsModel$updateItem updateItem updated server setting: ServerSetting(id=2, index=2, name=demo, url=http://demo.subsonic.org/, color=null, userName=guest2, password=guest, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=false, musicFolderId=null, minimumApiVersion=null, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null) 
14:25:34.255: D ActiveServerProvider$getActiveServer getActiveServer retrieved from DataBase, id: 2 cachedServer: ServerSetting(id=2, index=2, name=demo, url=http://demo.subsonic.org/, color=null, userName=guest2, password=guest, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=false, musicFolderId=null, minimumApiVersion=null, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null) 
14:25:37.512: D NavigationActivity Navigated to org.moire.ultrasonic:id/editServerFragment 
14:25:39.286: W EditServerFragment$testConnection$task com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.moire.ultrasonic.api.subsonic.response.SubsonicResponse` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 3, column: 7]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._unwrapAndDeserialize(ObjectReader.java:1703)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:75)
	at org.moire.ultrasonic.api.subsonic.VersionAwareJacksonConverterFactory$VersionAwareResponseBodyConverter.convert(VersionAwareJacksonConverterFactory.kt:66)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at org.moire.ultrasonic.fragment.EditServerFragment$testConnection$task$1.doInBackground(EditServerFragment.kt:411)
	at org.moire.ultrasonic.fragment.EditServerFragment$testConnection$task$1.doInBackground(EditServerFragment.kt:360)
	at org.moire.ultrasonic.util.ModalBackgroundTask$1.run(ModalBackgroundTask.java:74)
 com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.moire.ultrasonic.api.subsonic.response.SubsonicResponse` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 3, column: 7]
14:25:40.894: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
14:25:41.294: D NavigationActivity Navigated to org.moire.ultrasonic:id/settingsFragment 
14:25:42.261: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
14:25:43.997: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
14:25:44.023: I Storage StorageFile caches were reset 
14:25:45.558: D NavigationActivity Navigated to org.moire.ultrasonic:id/serverSelectorFragment 
14:25:46.327: I PlaybackStateSerializer Serialized currentPlayingIndex: -1, currentPlayingPosition: 0 
14:25:46.328: D ActiveServerProvider setActiveServerByIndex 1 
14:25:46.329: D JukeboxMediaPlayer Jukebox Service setting enabled to false 
14:25:46.332: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic/cache/downloadstate.ser 
14:25:47.331: D JukeboxMediaPlayer Stopped Jukebox Service 
14:25:47.335: I ServerSelectorFragment Active server was set to: 1 
14:25:47.339: D NavigationActivity Navigated to org.moire.ultrasonic:id/mainFragment 
```

**Comment by nitehu** [comment]
Its really strange, it seems Ultrasonic won't understand your server's response. Maybe the problem is in an updated library we're using.
Could you please write what server you're using? Name and version.
I'll try to reproduce the problem.

**Comment by fiskhandlarn** [comment]
@nitehu 

> 14:25:34.236: D ServerSettingsModel$updateItem updateItem updated server setting: ServerSetting(id=2, index=2, name=demo, url=http://demo.subsonic.org/, color=null, userName=guest2, password=guest, jukeboxByDefault=false, allowSelfSignedCertificate=false, ldapSupport=false, musicFolderId=null, minimumApiVersion=null, chatSupport=null, bookmarkSupport=null, shareSupport=null, podcastSupport=null) 

This is for http://demo.subsonic.org/login.view?user=guest1&password=guest which seems to be running [Subsonic Premium Version 6.1.6 (build 0cfa60)](http://demo.subsonic.org/help.view) (released November 10, 2019).
The same happens for my own server (which I won't post details about here) which runs Airsonic version 10.6.2-RELEASE (released May 3, 2020).

If you have a server which works for you guys maybe I can try it?

**Comment by nitehu** [comment]
Thank you for reporting this!
The error seems to be in the release version of 3.1.0, and we can't reproduce it during debug.
It [seems to be related](https://github.com/FasterXML/jackson-module-kotlin/issues/522#issuecomment-1018884860) to Kotlin 1.6 and R8. 
I'll try to fix this ASAP, stay tuned. Meanwhile, please do not use the 3.1.0 version. 
@ogarcia I'm not sure what the procedure is for bugs like this, can you remove this release until it is fixed?

**Comment by ogarcia** [comment]
@nitehu I mark it as a pre-release in GitHub and now latest release is 3.0.1. In Play Store I cannot do anything, but is published in beta channel (still under review) so affected people can opt-out to stable channel

**Comment by fiskhandlarn** [comment]
@ogarcia Thanks for the quick fix! Is it possible to have an .apk for the 3.1.1 release as well? :) https://github.com/ultrasonic/ultrasonic/releases/tag/3.1.1

**Comment by ogarcia** [comment]
@fiskhandlarn the CI is working on it :wink:

**Comment by ogarcia** [comment]
@fiskhandlarn Done. Please test it and tell us if work well

**Comment by fiskhandlarn** [comment]
@ogarcia OIC. Works perfectly, thanks!
