### ISSUE TITLE
Android Auto - Shuffle playlist

### ISSUE THREAD

**Issue by ParadingLunatic** [ogarcia/ultrasonic#693]
## Problem description

Just wondering if there's a way to play a playlist shuffled while using wired Android Auto.  I just got Ultrasonic (previously used dsub) and went for my first drive with it and didn't see a way to play a playlist shuffled, or shuffle a currently playing list.

### Steps to reproduce

While in Android Auto, Open Ultrasonic, go to playlists, select playlist.  Only visible option is to play, which plays in order.  After playing there doesn't appear to be a way to shuffle the playlist without opening Ultrasonic directly on the phone.

## System information

 * **Ultrasonic version**: 2.24 (from Play Store)
 * **Android version**: Android 11 (Nov 2021 patches)
 * **Device info**: OnePlus 6T

## Additional notes
Also noticed I had some disconnect issues which I never experienced while using dsub.  There was even a point after getting in the car where it went through a non-stop loop of connecting and disconnecting until I manually disconnected and reconnected.

**Comment by nitehu** [comment]
Yes, Android Auto is a new feature in Ultrasonic, there are still a few things missing from it, one of them is the shuffle/repeat setting.

**Comment by ParadingLunatic** [comment]
Just as a "kudos" since I've had some more time using Ultrasonic with Android Auto.  Just the fact that every single time I get in the car and fire up Android Auto that Ultrasonic continues exactly where I left off has made this my new music player regardless of the minor inconvenience of no shuffle option from the AA display.  With DSub almost every single time I got in the car it would completely forget the playlist it was playing and I'd have to go back in and start it over again.  It was extremely annoying.  

The only strange thing I get with Ultrasonic is when Android Auto first starts up and starts playing music, it'll pause after about 5-10 seconds of playing.  Then I have to wait about 4-5 seconds to play it again, otherwise it pauses immediately.  Once again though...this is an incredibly minor thing I can easily live with.  Thanks again for adding AA support!

Also, you guys really need to get the word out about AA support (if you're ready for an influx of users using it).  Right now as far as I'm aware, pretty much the only apps supporting Subsonic music server streaming is DSub and Ultrasonic.

**Comment by nitehu** [comment]
Thanks for letting us know, it really means a lot :)

**Comment by ogarcia** [comment]
Related to #756 (we only keep this issue open in the migration to GitLab)
