### ISSUE TITLE
Ultrasonic is activated with BT even when all media play functions are disabled

### ISSUE THREAD

**Issue by gerroon** [ogarcia/ultrasonic#696]
## Problem description

US seems to be activated when my phone connects to a BT device. Since I do not like this behavior I disabled all the media play button BT related functions in US and it still shows itself in the tray pulldown notification area.

### Steps to reproduce
Disable all media BT related functions in US
Enable Bluetooth

## System information

 * **Ultrasonic version**: 3.1.1
 * **Android version**: LineageOS 18.1
 * **Device info**: Pixel

**Comment by mradermaxlol** [comment]
Same here on a device running Omni 11.

**Comment by tzugen** [comment]
Without looking deeper into it I would guess there is a connection with #621

**Comment by tzugen** [comment]
Please check with #726
