### ISSUE TITLE
No sound after one track

### ISSUE THREAD

**Issue by hmueller01** [ogarcia/ultrasonic#697]
## Problem description

Sound output stops after one track. The time of the new/next track counts and the progress bar moves, but you can not hear the song. Pressing Pause/Play does not help. Pressing the Rewind or Forward button starts playback for exact one more track. Then the same starts again. No sound. It is with internal speaker as well as with bluetooth. So it might be different to #681. Downloading the tracks did not help.

### Steps to reproduce

Add some tracks to playback and start the first one.

## System information

 * **Ultrasonic version**: *3.1.1* apk from github release
 * **Android version**: *12 SQ1D.220205.004*
 * **Device info**: *Google Pixel 6*

## Additional notes

It is quite obvious a Google Pixel 6 problem, as many players have playback problems (e.g. Black Player, DS audio, [Hi-Fi Cast](https://groups.google.com/g/hi-cast-help-forum/c/demP73ji7Ig)). But it looks like VLC, BubbleUPnP (does have some audio dropouts, but keeps playing all tracks) and [Music-Player-GO](https://github.com/enricocid/Music-Player-GO) work.

**Comment by hmueller01** [comment]
It was working good with v3.0.0 and the problem raised after the upgrade to v3.1.1 (with prior uninstall because of different signing). In the meantime I cleaned the app data and for the moment the issue is gone. Will see if it comes again.

**Comment by nitehu** [comment]
Thanks for letting us know!
If you find the problem again, please help us by sending any logs (exception, debug, logcat) so we can see if there is an exception somewhere...

**Comment by hmueller01** [comment]
The problem came back. This time I activated the logging.

[ultrasonic.0.log](https://github.com/ultrasonic/ultrasonic/files/8309277/ultrasonic.0.log)
After playing track 1 as it should be, Ultrasonic started playing track 2 without sound. After a few seconds I pressed rewind and Ultrasonic started track 2 from the beginning with sound. After that I stopped the logging.

[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/8309278/ultrasonic.1.log)
Same example as above, but did not press anything. Just stopping the log during soundless track 2 to see the difference.

Maybe you can find something ...

**Comment by tzugen** [comment]
I am unclear what is the "second" track. I see tracks with track numbers 2 and 3 being played.
Please specify which track was working and which one was silent.

**Comment by tzugen** [comment]
Infinite Dreams was the silent one?

**Comment by tzugen** [comment]
This seems to be the relevant section:

```
10:19:59.794: I LocalMediaPlayer COMPLETED -> STARTED (DownloadFile (Entry(id=15689, parent=15623, isDirectory=false, title=Infinite Dreams, album=Seventh Son Of A Seventh Son, albumId=1095, artist=Iron Maiden, artistId=477, track=2, year=1988, genre=Heavy Metal, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=15623, size=7290880, songCount=null, duration=369, bitRate=157, path=Iron Maiden/1988_Seventh Son Of A Seventh Son/02 - Infinite Dreams.mp3, isVideo=false, starred=false, discNumber=-1, type=music, created=Mon Feb 02 18:11:49 GMT+01:00 2009, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null, name=null))) 
10:19:59.870: I BitmapUtils$Companion getBitmapFromDisk 240 
10:19:59.882: D MediaPlayerService Processed player state change 
10:19:59.883: D MediaSessionHandler Updating the MediaSession 
10:19:59.913: I BitmapUtils$Companion getBitmapFromDisk 1080 
10:19:59.964: I BitmapUtils$Companion getBitmapFromDisk 240 
10:19:59.967: D MediaPlayerService Processed player state change 
10:19:59.968: D MediaSessionHandler Updating the MediaSession 
10:19:59.989: I BitmapUtils$Companion getBitmapFromDisk 1080 
10:20:00.034: I BitmapUtils$Companion getBitmapFromDisk 240 
10:20:00.064: I BitmapUtils$Companion getBitmapFromDisk 672 
10:20:00.068: V MediaPlayerService Updated notification 
10:20:00.069: D MediaPlayerService Processed player state change 
10:20:00.069: D MediaSessionHandler Updating the MediaSession 
10:20:00.090: I BitmapUtils$Companion getBitmapFromDisk 1080 
10:20:00.112: I Downloader Downloader started 
10:20:00.112: W Downloader Checking Downloads 
10:20:00.117: V Downloader Downloader checkDownloadsInternal checking downloads 
10:20:00.236: I Downloader Downloader stopped 
10:20:00.241: I CancellableTask Cancelling CheckCompletionTask (DownloadFile (Entry(id=15689, parent=15623, isDirectory=false, title=Infinite Dreams, album=Seventh Son Of A Seventh Son, albumId=1095, artist=Iron Maiden, artistId=477, track=2, year=1988, genre=Heavy Metal, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=15623, size=7290880, songCount=null, duration=369, bitRate=157, path=Iron Maiden/1988_Seventh Son Of A Seventh Son/02 - Infinite Dreams.mp3, isVideo=false, starred=false, discNumber=-1, type=music, created=Mon Feb 02 18:11:49 GMT+01:00 2009, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null, name=null))) 
10:20:12.818: I Storage StorageFile caches were reset 
10:20:12.826: V BaseAdapter Received fresh list, size 8 
10:20:24.819: I LocalMediaPlayer STARTED -> PAUSED (DownloadFile (Entry(id=15689, parent=15623, isDirectory=false, title=Infinite Dreams, album=Seventh Son Of A Seventh Son, albumId=1095, artist=Iron Maiden, artistId=477, track=2, year=1988, genre=Heavy Metal, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=15623, size=7290880, songCount=null, duration=369, bitRate=157, path=Iron Maiden/1988_Seventh Son Of A Seventh Son/02 - Infinite Dreams.mp3, isVideo=false, starred=false, discNumber=-1, type=music, created=Mon Feb 02 18:11:49 GMT+01:00 2009, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null, name=null))) 
10:20:24.835: I PlaybackStateSerializer Serialized currentPlayingIndex: 1, currentPlayingPosition: 24758 
10:20:24.847: I FileUtil Serialized object to /data/user/0/org.moire.ultrasonic.debug/cache/downloadstate.ser 
```

Unfortunately I don't see anything unusual. @nitehu @ogarcia

**Comment by hmueller01** [comment]
Sorry for been a bit unclear. I startet track "01 Moonchild". After that I enabled logging. This song plays perfect. At the end of this song the player switches to track "02 Infinite Dreams". No no sound is played. "03 Can I Play With Madness" it the next song which was not played (as I stopped logging).

If the player switches (track 01 -> 02)
```
LocalMediaPlayer STARTED -> COMPLETED 
LocalMediaPlayer COMPLETED -> STARTED
```
it does not work (see both log files). 
If rewind the song (track 02 -> 02) the switch sequence is like this (see ultrasonic.0.log):
```
LocalMediaPlayer STARTED -> IDLE
LocalMediaPlayer IDLE -> PREPARING
LocalMediaPlayer PREPARING -> PREPARED
LocalMediaPlayer PREPARED  -> STARTED
```
And this works. So maybe we have to look into this difference.

**Comment by hmueller01** [comment]
What also **NOT** works is pressing the Pause/Play button:
```
LocalMediaPlayer STARTED -> PAUSED
LocalMediaPlayer PAUSED  -> STARTED
```
But if I move the position slider (just tapping on it is enough) during silent play the sound starts as well. But here I see no debugging output ...

**Comment by tzugen** [comment]
I think I had nearly/exactly the same issue about a year ago...

See https://github.com/ultrasonic/ultrasonic/issues/378

**Comment by hmueller01** [comment]
> I think I had nearly/exactly the same issue about a year ago...
> 
> See #378

It sounds similar but is still different in some details.

> Sometimes I play an album, and after a few songs, the music stops.
> When I unlock the phone, I see that Ultrasonic thinks its playing music, but there is no audio output.
> Skipiping to the next song usually does **not** fix the problem.
> Pausing and unpausing **usually** fixes the problem.

Pausing and unpausing does **not** help. Skipping back or forward to the next song **always** helps.

Last time resetting app data helped. I didn't do this yet in case I can test something to localize the problem.

**Comment by tzugen** [comment]
You could try to set some breakpoints in LocalMediaPlayer. This is where everything happens..
It might be a bug with the Android Mediaplayer component.

**Comment by hmueller01** [comment]
After seeing that seeking in the song starts playback I debugged and poked around a bit and found that [fix](https://github.com/ultrasonic/ultrasonic/compare/develop...hmueller01:fix-no-sound?expand=1). Don't know why this is need, but it helps in my case. If you like I make a pull.

**Comment by nitehu** [comment]
So if I understand correctly, just seeking to the beginning of a song when it starts playing helps?

**Comment by hmueller01** [comment]
I think it does not depend where to seek (ok, in some point it depends as you want to hear the song from the beginning). The crazy thing is, that if you ask the mediaPlayer before the seek `mediaPlayer.getCurrentPosition()` it returns 0.
I think it's a kind of bug in Google's mediaplayer, as lots of players have problems ...

**Comment by tzugen** [comment]
OK it makes sense. I suspected this to be a platform bug.
Are we sure that we initialize the media player correctly?

**Comment by tzugen** [comment]
> I think it does not depend where to seek (ok, in some point it depends as you want to hear the song from the beginning). The crazy thing is, that if you ask the mediaPlayer before the seek `mediaPlayer.getCurrentPosition()` it returns 0. I think it's a kind of bug in Google's mediaplayer, as lots of players have problems ...

But 0 would be correct, no?

**Comment by hmueller01** [comment]
I added that in my test, as I thought the `nextMediaPlayer` was set to a wrong position. But I think 0 is correct, isn't it?
Maybe there is somewhere a problem with the init of the player and this seek just helps. I do not know.

**Comment by hmueller01** [comment]
BTW why starts the nextMediaPlayer anyway? I haven't found a `nextMediaPlayer.start()` nor a `mediaPlayer.start()` after the `mediaPlayer = nextMediaPlayer!!` in method `playNext()`. But maybe I haven't fully understood the code.

```
       mediaPlayer = nextMediaPlayer!!
        // TODO: hmueller01
        // Fix problem with Google Pixel 6 Android 12 devices not playing the next song
        Timber.v("mediaPlayer.isPlaying vor seek: %b", mediaPlayer.isPlaying)
        mediaPlayer.seekTo(0)
        Timber.v("mediaPlayer.isPlaying nach seek: %b", mediaPlayer.isPlaying)
```
And `mediaPlayer.isPlaying` is `true` in both cases. Shouldn't the nextMediaPlayer be stopped until it is used?

**Comment by tzugen** [comment]
> BTW why starts the nextMediaPlayer anyway? I haven't found a `nextMediaPlayer.start()` nor a `mediaPlayer.start()` after the `mediaPlayer = nextMediaPlayer!!` in method `playNext()`. But maybe I haven't fully understood the code.

Everything comes from `override fun onCompletion(mediaPlayer: MediaPlayer) {` in LocalMediaPlayer. There `onSongCompleted` is called, which for some reasons is called in MediaPlayerService, and then jumps back to `fun play(index: Int) {`....

Full stack:
```
2022-03-27 20:39:41.898 19260-19260/org.moire.ultrasonic.debug W/System.err: java.lang.Exception: Stack trace
2022-03-27 20:39:41.902 19260-19260/org.moire.ultrasonic.debug W/System.err:     at java.lang.Thread.dumpStack(Thread.java:1529)
2022-03-27 20:39:41.904 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer.doPlay(LocalMediaPlayer.kt:341)
2022-03-27 20:39:41.907 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer.bufferAndPlay(LocalMediaPlayer.kt:335)
2022-03-27 20:39:41.910 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer.play(LocalMediaPlayer.kt:238)
2022-03-27 20:39:41.913 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer.play$default(LocalMediaPlayer.kt:230)
2022-03-27 20:39:41.916 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.MediaPlayerService.play(MediaPlayerService.kt:292)
2022-03-27 20:39:41.924 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.MediaPlayerService.play(MediaPlayerService.kt:278)
2022-03-27 20:39:41.926 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.MediaPlayerService$setupOnSongCompletedHandler$1.invoke(MediaPlayerService.kt:446)
2022-03-27 20:39:41.929 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.MediaPlayerService$setupOnSongCompletedHandler$1.invoke(MediaPlayerService.kt:423)
2022-03-27 20:39:41.931 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer$attachHandlersToPlayer$2.onCompletion$lambda-0(LocalMediaPlayer.kt:539)
2022-03-27 20:39:41.933 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer$attachHandlersToPlayer$2.$r8$lambda$HPJTDuEehJvrcwPoU5mQ3O0Gg8E(Unknown Source:0)
2022-03-27 20:39:41.936 19260-19260/org.moire.ultrasonic.debug W/System.err:     at org.moire.ultrasonic.service.LocalMediaPlayer$attachHandlersToPlayer$2$$ExternalSyntheticLambda0.run(Unknown Source:2)
```

**Comment by tzugen** [comment]
@hmueller01 Do you have gapless playback activated?

**Comment by hmueller01** [comment]
> @hmueller01 Do you have gapless playback activated?

Oh yes. Now I understand why it went away when I resetted the app data. And it came back after enabling it again.

**Comment by tzugen** [comment]
Ok, then it makes sense. It seems to be two completely different codepaths. Kind of a nightmare to maintain. I have written more about it in the discussion #724

**Comment by tzugen** [comment]
Please check with #726
