### ISSUE TITLE
Track based context menus do not function correctly in most fragments

### ISSUE THREAD

**Issue by omgcem** [ogarcia/ultrasonic#698]
## Problem description

Context menus under track based fragments (except Search) don't perform any actions.

### Steps to reproduce

Navigate to Media Library and select any Artist and Album
Long press to bring up context menu
Select play now or any other action and nothing will occur

## System information

 * **Ultrasonic version**: Self built from develop branch
 * **Android version**: Android 12
 * **Device info**: Samsung S10

## Additional notes

I've been looking at making some adjustments to the bookmark fragment for personal use and noticed that there appears to be some inconsistency between the ids under the xml defined layout and the event handler in the fragment file. 

https://github.com/ultrasonic/ultrasonic/blob/82d90a6aee972d5d02b222354c20d66261498d7b/ultrasonic/src/main/kotlin/org/moire/ultrasonic/adapters/TrackViewBinder.kt#L28

https://github.com/ultrasonic/ultrasonic/blob/82d90a6aee972d5d02b222354c20d66261498d7b/ultrasonic/src/main/res/menu/context_menu_track.xml#L5-L23

https://github.com/ultrasonic/ultrasonic/blob/82d90a6aee972d5d02b222354c20d66261498d7b/ultrasonic/src/main/kotlin/org/moire/ultrasonic/fragment/TrackCollectionFragment.kt#L633-L679

**Comment by nitehu** [comment]
Thanks for finding this.
(I wasn't even aware there was a context menu on those items :Đ )
