### ISSUE TITLE
Buffer size option

### ISSUE THREAD

**Issue by HenkBezuidenhout** [ogarcia/ultrasonic#7]
When using an OGG vorbis transcoder, Ultrasonic seems to be unable to detect the length of buffered data. It waits for the entire file to be downloaded before playing. This is no an issue when the connection is fast, but when it slows down, it can take minutes for a track to start playing, even though in my case 100kB of data is around 30 seconds of audio.

An easy fix would be to add an option to wait for a certain amount of data to be buffered, instead of waiting for a specific length of audio.

**Comment by ogarcia** [comment]
You have an option in settings to set the buffer length but I think that your issue is with subsonic server.

**Comment by HenkBezuidenhout** [comment]
That's odd, it was working with other players just fine. Winamp and VLC had no issues playing the OGG streams.

**Comment by HenkBezuidenhout** [comment]
Sorry only noticed now that this was asked in May last year already. My apologies for the delay in the response. I've since switched to alternative platforms for music streaming.
