### ISSUE TITLE
M3U playlists are all empty due to properly encoded URLs

### ISSUE THREAD

**Issue by Siress** [ogarcia/ultrasonic#700]
## Problem description

Imported M3U playlists are all empty.

### Steps to reproduce

Generate M3U with proper URLs for songs. See 'Additional Notes' for example.

## System information

Android 12

### Ultrasonic client

 * **Ultrasonic version**: 2.24.0
 * **Android version**: 12
 * **Device info**: Pixel 3a

### Server

Navidrome docker.

## Additional notes

My M3U playlists all have encoded URLs for file locations that are not recognized by Ultrasonic. This is common among other software, but it's in defiance of the URL standard IETF RFC3986. Decoding the characters restores functionality. More on this topic from the perspective of a VLC maintainer can be found [here](https://forum.videolan.org/viewtopic.php?p=476034#p476034) and [here](https://code.videolan.org/videolan/vlc/-/issues/26698) Really, then, this is a request to 'adopt the URL standard in defiance of convention.' I'd like to think that encoded/decoded could be determined automatically by Ultrasonic (e.g. if file not found, decode and try again before moving to the next file; if decoded file found then continue decoding until otherwise instructed.)

For example, this is what is generated:

```
#EXTM3U
#EXTINF:275,Hans Zimmer - Time
Hans%20Zimmer/Hans%20Zimmer%20-%20Time.mp3
#EXTINF:257,Hans Zimmer - Ride
Hans%20Zimmer/Hans%20Zimmer%20-%20Ride.mp3
```
And this is what Ultrasonic seems to require:
```
#EXTM3U
#EXTINF:275,Hans Zimmer - Time
Hans Zimmer/Hans Zimmer - Time.mp3
#EXTINF:257,Hans Zimmer - Ride
Hans Zimmer/Hans Zimmer - Ride.mp3
```

**Comment by ogarcia** [comment]
As far as I know, the playlists are controlled by the Subsonic API server and presented to Ultrasonic with [API format](http://www.subsonic.org/pages/inc/api/examples/playlist_example_1.xml). Ultrasonic doesn't manage M3U files in any form so if your server doesn`t support URL encoded scheme, you should open a bug to them.

Anyway the sample file with the URL scheme is wrong. It lakes the `file://`.

**Comment by Siress** [comment]
Thanks for taking a look.

Edit: misunderstood your point about the server at first. So you're saying this is handled by Navidrome. I'll add that detail above, but I think this behavior is the same for locally stored files (i.e server is irrelevant).

That sounds like an absolute path name, where as it's better to have relative paths so that I can move my music folder around without breaking the playlists.

**Comment by ogarcia** [comment]
As I said, Ultrasonic doesn't load M3U files. The playlists are loaded by server and offer them to Ultrasonic using the API, so if the lists appear blank is because the server is not able to interpret them.

**Comment by nitehu** [comment]
Just to be sure, @Siress are you talking about using Ultrasonic in offline mode?

When you are connected to a server, the server handles all the playlists and .m3u files, as ogarcia mentioned.
When you are in offline mode, Ultrasonic tries to read and write .m3u files (and most of the time fails miserably, as offline mode is a bit buggy).

Which use case has this issue?

**Comment by ogarcia** [comment]
> Ultrasonic tries to read and write .m3u files (and most of the time fails miserably, as offline mode is a bit buggy)

Yes. In fact in offline mode we only have _null pointer exceptions_ :joy:

**Comment by Siress** [comment]
Ah. I see. I was talking about online mode.
I take it that this belongs as a Navidrome feature request, then. Thanks!
