### ISSUE TITLE
Show Downloads on Play

### ISSUE THREAD

**Issue by hmueller01** [ogarcia/ultrasonic#702]
## Problem description

I think the logic behind 
```
<string name="settings.download_transition">Show Downloads on Play</string>
```
```
Settings.shouldTransitionOnPlayback
```
is mixed-up, as if it is activated the screen jumps to the player if play is pressed and stays in download if not activated.

I would suggest to rename this string to _**Stay in Downloads on Play**_.

### Steps to reproduce

Enable and disable the setting above and press play in the album list of the media library.

### Ultrasonic client

 * **Ultrasonic version**: *3.1.1*
 * **Android version**: *12*
 * **Device info**: *Pixel 6*

### Server

 * **Server name**: *Airsonic*
 * **Server version**: *10.6.2*

**Comment by ogarcia** [comment]
LGTM. @hmueller01 please include this in your #703 proposal

**Comment by hmueller01** [comment]
Sorry, I think my suggestion **_Stay in Downloads on Play_** wasn't that good. It is still not correct.
Maybe I was confused because of the different German translation. I just installed English language on my phone to better test this.
If this option is activated the Now Playing fragment is shown. 
My new proposal is to change the strings to
```
    <string name="settings.download_transition">Show Now Playing after Download</string>
    <string name="settings.download_transition_summary">Switch to Now Playing after starting playback in media view</string>
```
I am not so sure about the _Download_, as this might be misleading for the user. What do you think?

**Comment by nitehu** [comment]
I think the "Downloads" is a legacy term, which isn't used anymore in Ultrasonic. Before we've started a bigger refactor, there was a "download view", which actually showed the music player controls / playlist. My guess is that in the past the terminology meant that the view was responsible for showing the actually downloading and playing songs - but we started to use some more common terms found in other media players.

So I think the greatest help would be if you'd translate this to something that makes the most sense for you :)

**Comment by ogarcia** [comment]
What about use:
```
<string name="settings.download_transition">Show Now Playing after playback</string>
```

**Comment by hmueller01** [comment]
Ok,  I was thinking about that once more. @ogarcia you suggestion is ok, but how about this one:
```
<string name="settings.download_transition">Show Now Playing after pressing play</string>
```
Don't know if it is really good English, but it sounds a little bit more logic to me together with the summary explaination.
```
<string name="settings.download_transition_summary">Switch to Now Playing after starting playback in media view</string>
```
