### ISSUE TITLE
showAllSongsByArtist not working

### ISSUE THREAD

**Issue by hmueller01** [ogarcia/ultrasonic#709]
## Problem description

There is a checkbox in the settings without any code behind.
```
        <CheckBoxPreference
            a:defaultValue="false"
            a:key="showAllSongsByArtist"
            a:summary="@string/settings.show_all_songs_by_artist_summary"
            a:title="@string/settings.show_all_songs_by_artist"
            app:iconSpaceReserved="false"/>
```

Is it planned to implement that? So should we set `app:isPreferenceVisible="false"` for the moment or remove this completely?

**Comment by tzugen** [comment]
It was broken for a while now. I guess the checkbox can be removed, unless someone is motivated to maintain the feature,
but it seems to be so rarely used..
