### ISSUE TITLE
Feature Request: per server option to cache all songs for offline use.

### ISSUE THREAD

**Issue by zombiehoffa** [ogarcia/ultrasonic#715]
## Problem description
It would be nice to have a per server option to cache all songs for offline play.

**Comment by nitehu** [comment]
Would you please describe this a bit? 
By "all songs" do you mean that the entire music library would be downloaded from the server to the phone, to be available for offline use? Would this be similar to how Pinning currently works, just "pinning" the entire contents of the server?

**Comment by zombiehoffa** [comment]
I don't know how pinning currently works, as I didn't find documentation to try that/what it does. Yes, I would like to have an option to download the entire music library from the server to the phone to be available for offline use and to keep that offline use music synced with the server (so if something is deleted or changed on the server it is redownloaded/deleted in the offline cache). If pinning works like that it will probably solve my problem, albeit in a more tedious way than I would prefer, as I will have to pin hundreds of artists and then remember to pin new artists.


I tried changing the caching settings to accomplish this (as that is basically how you do it in subsonic) and I ended up with multiple copies of songs in the cache dir without the directory structure. It would be best if this offline cache kept the directory structure implied by the subsonic server (in my case artist/album/song) to make the music more useful for other program and also didn't have duplicates unless there are duplicates on the server itself being served to ultrasonic.

**Comment by nitehu** [comment]
Oh ok, I think I understand now.

> so if something is deleted or changed on the server it is redownloaded/deleted in the offline cache

Unfortunately that isn't trivial to solve using the subsonic API, as clients won't get notified about the changes.
Maybe it can be solved by scanning the entire library periodically.
However, I think for this use case a file synchronization app would be better (like e.g. google drive, or owncloud or something similar).

**Comment by zombiehoffa** [comment]
Well, even just keeping the files in sync so that there is a corresponding file on phone in a reasonable directory structure for everything offered via subsonic would be a huge step in the right direction for my use case. Yes, I am solving this issue right now by running beets in a docker container to transcode my whole collection into the opus format into another directory and then syncing that directory to my phone with syncthing.  It's not as ideal as just having the subsonic client handle it  because it is a lot more complex and takes a lot more drive space, while also losing out on listenbrainz and/or lastfm scrobbling (without added complexity). It's also a lot clunkier switching clients whenever I leave the house to avoid cell data usage.

**Comment by ogarcia** [comment]
As nitehu says, the method to keep any element in your device is _pinning_ it. Maintain your entire collection in sync with your device is the task of other types of applications such as the one you mention _syncthing_ (which I think is the best system currently available for keeping files synchronized).

My advice is that for what you want to do, use a local music player (like [Auxio][1] or [Music Player GO][2]) and [Simple Scrobbler][3] to get the functionality of scrobbling and forget about subsonic as it is not intended for what you are looking for.

What's more, you already mention that you use beets. There is currently no better music organizer. So you won't have any problem to keep your music in order. It is true that if you have your music stored in FLAC and you want it on your device in OPUS you have to transcode it and it will take up more space, but there is little you can do against that. The only thing you can do is to synchronize the OPUS music only between your mobile devices, but that would force you to "upload the music" to one of them using another method.

[1]: https://github.com/OxygenCobalt/Auxio
[2]: https://github.com/enricocid/Music-Player-GO
[3]: https://github.com/simple-last-fm-scrobbler/sls

**Comment by ogarcia** [comment]
We are closing this issue as it is not something that can be implemented in Ultrasonic.
