### ISSUE TITLE
Insert after current song not fully working

### ISSUE THREAD

**Issue by hmueller01** [ogarcia/ultrasonic#717]
## Problem description

Adding a song after the current song gets not played.

### Steps to reproduce

Add songs to the playlist and start playing. Choose another song and add it after the current song.
It gets correctly added/displayed after the current song in the Now Playing list. But after the current songs ends it gets skipped and playback continues after the added song. 

### Ultrasonic client

 * **Ultrasonic version**: *3.1.1++ debug build*
 * **Android version**: *12 (SP2A.220305.013)*
 * **Device info**: *Pixel 6*

## Additional notes

Skipping backwards with the button plays the added song. Also skipping from the current playing song with the button to the next plays it correctly. So it looks like the next song is in the nextMediaPlayer before and gets not replaced by the newly added song in "auto-play-mode".

**Comment by tzugen** [comment]
Please check this with #726

**Comment by hmueller01** [comment]
#726 fixes this.
