### ISSUE TITLE
No longer showing any track data via bluetooth

### ISSUE THREAD

**Issue by Bidley** [ogarcia/ultrasonic#735]
## Problem description

When connected to my car (Skoda Yeti) stereo and my AV receiver (Onkyo TX-686), no song info is displayed, but audio plays fine. I have tried other apps with the same phone, and they all pass the info on fine. It's been getting gradually worse over the last few months (started with no timer, then occasionally wouldn't change info when the track changes, then suddenly no info at all).

All songs are downloaded to cache while playing. Works fine when connected via laptop (bluetooth) and web browser (Navidrome native client)

### Steps to reproduce

Connect to stereo via bluetooth, play a song and see if the song info comes up on the playback device.

### Ultrasonic client

 * **Ultrasonic version**: *3.1.1*
 * **Android version**: *12*
 * **Device info**: *Google Pixel 4a*

### Server

 * **Server name**: *Navidrome*
 * **Server version**: *0.47.5*
 * **Protocol used**: *https, nginx proxy manager/letsencrypt*

**Comment by fexofenadine** [comment]
There's a setting that was created to fix this issue (bluetooth info on older head units (issue 581)). Go to Settings --> Notifications --> Disable Sending of Now Playing List

You may need to change the AVRCP version in your Developer Options also

All that said, this particular option has been flaky for me this past couple of months though. The info stops displaying after a couple of days and I have to reset the app back to defaults and set it up again

**Comment by fexofenadine** [comment]
Actually my car will only show the first track now and won't update to the next one(s) after that. It does show the progress through the track however, just no other details

**Comment by Bidley** [comment]
> There's a setting that was created to fix this issue (bluetooth info on older head units (issue 581)). Go to Settings --> Notifications --> Disable Sending of Now Playing List
> 
> You may need to change the AVRCP version in your Developer Options also
> 
> All that said, this particular option has been flaky for me this past couple of months though. The info stops displaying after a couple of days and I have to reset the app back to defaults and set it up again

Thanks, the "Disable Sending of Now Playing List" setting and a phone reboot fixed this.

**Comment by Bidley** [comment]
This no longer works after the last security update to Android 12.

**Comment by Bidley** [comment]
Well I uninstalled, then reinstalled and it started working normally again. Worked fine for perhaps a couple of weeks, and now it's just randomly stopped working again. Guess I'll try Substreamer.

**Comment by tzugen** [comment]
We are getting closer to finishing the rebuilding of the playback infrastructure.
Would be great if you could check if it is still happening with the current beta...
https://github.com/ultrasonic/ultrasonic/releases/
