### ISSUE TITLE
handling of reverse proxy subdirectories

### ISSUE THREAD

**Issue by thtwice** [ogarcia/ultrasonic#736]
Hi,
I suppose this is more of a feature request than a bug.

My navidrome server sits behind a reverse proxy inside a subfolder in my domain.
I setup navidrome to handle the base_url using the relative enviroment option when creating the docker container.
My caddyfile:
```
https://somedomain.duckdns.org {
	reverse_proxy /navidrome/* internalip:4533
}
```
Seems like Ultrasonic doesn't support this kind of setup giving me a connection error if I try to connect to the server:
```
Error
Connection failure. Didn't understand the reply. Please check the server address.
```

The webui for navidrome works without problem.

-----------------------------------------------------------------------------------------------------------------------------
Btw, if I put the server on a domain by itself everything works:
```
https://dedicatednavidromedomain.duckdns.org {
	reverse_proxy internalip:4533
}
```

**Comment by ogarcia** [comment]
This is a configuration problem in your setup. Do you try to configure Server Address as `https://somedomain.duckdns.org/navidrome/`?

**Comment by thtwice** [comment]
> This is a configuration problem in your setup. Do you try to configure Server Address as `https://somedomain.duckdns.org/navidrome/`?

Yes I did. 
As far as I can tell it's configured correctly. 
Even the webui loads if I go to 
`https://somedomain.duckdns.org/navidrome/`

Do you think there is something else I should check?

PS: forgot to add that DSub with the same setup manages to get a connection

**Comment by thtwice** [comment]
Ok, this is properly wierd.
Every single reverse proxy subdirectory that I set up required the trailing slash at the end. 
Even the webui for navidrome loads only if I go to `https://somedomain.duckdns.org/navidrome/`

But not if I go to` https://somedomain.duckdns.org/navidrome`

In Subsonic settings works the other way around. When I put the slash at the end I get the error message but without it everything works.

If someone ends up here with the same problem as me just try putting the address in without the slash at the end and it should work.
