### ISSUE TITLE
App no longer appears as running or in notifications when resuming playback after wake

### ISSUE THREAD

**Issue by bobreidx** [ogarcia/ultrasonic#738]
## Problem description
When my Pixel 4a 5g wakes, Ultrasonic will start playing the last stream selected, and the app does not show up in Notifications or as a running app in any normal view (hence no user accessible media control over playback). I had to enable Developer Options to discover that it was in fact Ultrasonic in order to stop playback.

### Steps to reproduce
Select a remote or local file for playback (remote, in this case),
Begin playning the track.
Pause during playback.
Sleep the device. Wait n.
Unlock the device, at which point playback will resume (not ideal).
Swipe down to try and find Ultrasonic's media controls in the Notifications view (missing in my case).
Go to Settings > Apps to find Ultrasonic in the recent apps (missing in my case)
(without knowing that it is Ultrasonic engaged in playback, discovery of the running process will necessitate enabling Developer Options to find which background process is active).

## System information
Pixel 4a 5g
Android 12, build SP2A.220405.003

### Ultrasonic client
Ultrasonic 3.1.1
Android 12, build SP2A.220405.003
Google Pixel 4a (5g)

**Comment by tzugen** [comment]
Please check if this is still an issue with the upcoming beta release:
https://github.com/ultrasonic/ultrasonic/releases/
