### ISSUE TITLE
add more preload values

### ISSUE THREAD

**Issue by thigg** [ogarcia/ultrasonic#739]
## Problem description
I tend to preload my audiobooks, but some audiobooks have quite many files, thus preloading 10 files is not quite a lot
and preloading all is too much.

### Steps to reproduce

Have an audiobook with 500 files and be an hour without internet

### Ultrasonic client

 * **Ultrasonic version**: 3.2.0

## Additional notes

I would propose to either add a slider instead of fixed values that ranges 1..1000,all or to add 15,25,50,100 as options.

**Comment by tzugen** [comment]
Select all and downloading is not an option, because that would be too much?

**Comment by thigg** [comment]
Exactly, that would defeat the purpose here. I find it convinient, that I can switch vetween audiobooks without havibg them all at once in my device but only the next hour of where I currently am

**Comment by tzugen** [comment]
I tried to add a Slider, but there is no way to make it an exponential setting.
Then it's very hard to select in the low ranges.
Therefore I have simply added more values until 1000
