### ISSUE TITLE
Pinned/downloaded music gets wiped/deleted on exit & start

### ISSUE THREAD

**Issue by sochotnicky** [ogarcia/ultrasonic#742]
## Problem description

I have a couple albums from my collection that I want to have available offline at all times so I pinned them and they get downloaded.

However as soon as I hit exit and then restart the app - pinned music gets deleted and I have to re-download again. I have not figured out what triggers this behaviour. The pinned flag gets removed as well as if I never set it. 

### Steps to reproduce

1. Pin a single song and let it download. Switch to offline and verify it's available.
2. Go to sidebar, hit exit and then restart the app. 
3. Notice that the pinned music is not available anymore

## System information
Asus zenphone 8

### Ultrasonic client

 * **Ultrasonic version**: *3.2.0*
 * **Android version**: *12*
 * **Device info**: *Asus zenphone 8*

### Server

 * **Server name**: *Navidrome*
 * **Server version**: *0.47.5*
 * **Protocol used**: *https (letsencrypt)*

## Additional notes

I feel like I must be doing something completely wrong to be hitting this because I see no similar bugreports and I am sure others use the app just like that so maybe I am misunderstanding how cache is supposed to work etc. If there's a better way to download and keep around a bunch of albums - maybe I am just being dumb.

I have set the cache to be unlimited and tried setting "songs to preload" to unlimited as well but nothing helps

**Comment by sochotnicky** [comment]
It currently *looks* like if I use just "download" instead of "pin" the music does not get wiped. Have I misunderstood what "pin" is for? I could not find any documentation about it so I just guessed it meant "download and keep it around" (vs ordinary download which I though might get wiped when cache gets cleaned)

**Comment by tzugen** [comment]
Hi!
First of all your understanding of pin is correct. It means "download and keep around".
Since there are a bunch of changes in this area coming up in the next release, maybe you could check if it still happens in the beta release?

https://github.com/ultrasonic/ultrasonic/releases/

**Comment by sochotnicky** [comment]
I did a very cursory quick install + test of 4.0.0 beta. The new version looks to be working as expected as far as I can tell. If there's anything else I should look at/test while I am at it - let me know. I'll play around over the next few days/weeks

**Comment by tzugen** [comment]
OK, I'll close it then. If you see the behaviour again on the beta branch just reopen.

Regarding testing, we mainly worked on the playback stuff so if any problems show up there, you can open a bug or leave a comment here:
https://github.com/ultrasonic/ultrasonic/issues?q=is%3Aissue+is%3Aopen+author%3ABreak-Off

**Comment by ogarcia** [comment]
Fixed by #726
