### ISSUE TITLE
Can't install Media3-Beta 

### ISSUE THREAD

**Issue by Break-Off** [ogarcia/ultrasonic#744]
I can't install. It was first detected by Google Play Protect but even after disabling it says "App not installed.". Running stock ROM Android 11 on rooted Samsung Galaxy A51 (SM-A516B/DS). Thanks for your work.

_Originally posted by @Break-Off in https://github.com/ultrasonic/ultrasonic/discussions/743#discussioncomment-2855242_

**Comment by fexofenadine** [comment]
Just chiming in to say I had this same issue but a new build was posted after that which installs ok. Try the new download and give that a shot

**Comment by Break-Off** [comment]
Thanks for your comment. Actually, I was able to install it, just that this issue is a mirror of the comment thread. I forgot to close it.
