### ISSUE TITLE
Media3-Beta Feedback

### ISSUE THREAD

**Issue by Break-Off** [ogarcia/ultrasonic#745]
## Feedback
I've been testing the Media3 Beta for a few days. No problems whatsoever. Bluetooth and Android Auto works.

Only issue I've encountered is that Android Auto only displays the name of the song, anything else (artist, album, cover art) is not shown.

Thanks for your work. Ultrasonic rocks!

### Ultrasonic client

 * **Ultrasonic version**: *Media3-Beta*
 * **Android version**: *Rooted Android 11*
 * **Device info**: *Samsung A51 5G*

### Server

 * **Server name**: *Airsonic Advanced*
 * **Server version**: *11.0.0-SNAPSHOT.20220418221611*
 * **Protocol used**: *HTTPS, Let's Encrypt*

**Comment by Break-Off** [comment]
Ok, scratch that. I've been testing Android Auto a bit more and I can't put any new songs in the playlist. Using it from my phone works, but from the Android Auto screen doesnt't. When selecting Play All, it does a "going into subdirectory" animation and then ends in the same place. Individual songs don't work either.

**Comment by tzugen** [comment]
Hi thanks for having a look.
I see you were also the person who reported the bug about the Android Auto regression in version 3.x.x => #687 
Can you report in how far the situation is different now?

**Comment by ogarcia** [comment]
I have just opened #753 to address this issue. I have opened it as a new issue to avoid modifying this one and to be able to give an explanation of where to download the beta. If you want you can follow the discussion in that new issue (or in this one, now they are linked).

**Comment by Break-Off** [comment]
> Hi thanks for having a look. I see you were also the person who reported the bug about the Android Auto regression in version 3.x.x => #687 Can you report in how far the situation is different now?

Well, it works, in contrast to 3.x.x where it didn't, but it's not usable from the Android Auto interface. Selecting songs or albums make the player go into "pseudo-directories" where it ends back to where it was, without playing any new content. Playing content straight from the phone works as expected. Apart from that, no metadata is displayed about the song except the title itself: no artist, no album, no duration, etc. Previous/next song and play/pause works, though.

**Comment by tzugen** [comment]
I have put the Android Auto into a new bug. If you have more issues best put them either there or to the other bug that ogarcia created...
