### ISSUE TITLE
Ultrasonic not downloading any track

### ISSUE THREAD

**Issue by rombat** [ogarcia/ultrasonic#747]
## Problem description

Ultrasonic is seeing my navidrome (subsonic) server just fine, since I can browse and search everything without any problem. I can even rate tracks !
The problem I have is whenever I try to play (and thus, download) a track, I have this message showing in the middle of the screen: "Warning: no network available" (My app is in french so not sure it's the exact sentence in english).
Even if I've unchecked the "Download on Wi-Fi only" option, and for what it's worth, even if I am only on a WiFi network.

### Steps to reproduce
 see above

### Ultrasonic client

 * **Ultrasonic version**: 3.1.1 downloaded on Play Store
 * **Android version**:  8.0.0
 * **Device info**: Samsung Galaxy A5 2017

### Server

 * **Server name**: Navidrome (Subsonic API v1.16.1)
 * **Server version**: 0.47.5
 * **Protocol used**: https, let's encrypt certificate

**Comment by tzugen** [comment]
Hi!
Thanks for reporting. Could you check if it is still an issue on the beta release:
https://github.com/ultrasonic/ultrasonic/releases/
