### ISSUE TITLE
Ultrasonic 4.0.0-beta.X feedback

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/ultrasonic#753]
## Where to download

Go to https://github.com/ultrasonic/ultrasonic/releases and donwload latest 4.0.0-beta.X pre-release.

If you have been using Ultrasonic from the GitHub versions you can simply upgrade, but if you are using the Google Play Store or F-Droid version you must uninstall it first (you will lose your settings).

## Expected changes in behavior when switching to Media3 with ExoPlayer

In versions earlier than Android 10 ExoPlayer [may consume more battery power](https://exoplayer.dev/battery-consumption.html#audio-playback). In any case, the improvements offered by ExoPlayer make it worth the potential impact. If you have a device running Android 9 or earlier and the change is too much for you, we recommend that you download the latest version 3.X.X available from [the releases section](https://github.com/ultrasonic/ultrasonic/releases) and do not upgrade Ultrasonic.

### Known Issues
* The play queue size is limited to 2000 entries at a time.

**Comment by sserenade** [comment]
Thanks so much for your work on this! I am testing this today, so far all seems to work well. I am on a Pixel 6 Pro (12 (SQ3A.220605.009.B1)).

Things I have noticed so far:
 - The app doesn't prompt me for media storage permissions, but I can grant it in app info. I haven't noticed any odd behavior yet if it is not granted.
 - The debug logs mention that it can't delete the "partial" file after downloading a track is finished, but the file is not present when I go to look for it, so it seems to delete successfully. Granting storage permissions doesn't stop this log entry from appearing. It's not a serious issue, since usage isn't impacted.

```
11:10:24.712: W Downloader$downloadChecker Checking Downloads 
11:10:24.717: V Downloader Downloader checkDownloadsInternal checking downloads 
11:10:24.718: E DownloadFile CLEANING 
11:10:24.719: W Storage Failed to delete file /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/G Jones/Acid Disk 2/05-Flex Acid.partial.mp3 
11:10:24.724: I DownloadService DownloadService stopped 
11:10:24.729: I Downloader Downloader stopped 
11:10:24.730: I DownloadService DownloadService destroyed 
11:11:02.211: I MediaPlayerController$onCreate Media3 Event, event type: 3 
11:11:02.289: I MediaPlayerController$onCreate Media3 Event, event type: 3 
```

 -  No album art appears in the media notification, but I'm not sure if this is related to the beta or not - I had the previous app version's notification hidden since it would create the empty notification.

Let me know if a separate issue should be opened or if you'd like to continue to receive feedback here.

**Comment by ogarcia** [comment]
### Strange behavior in device rotation

When you are playing a song and you rotate the device several strange things happen:
1. Playback stops for a moment.
2. The song progress bar stops working.
3. The disc cover is no longer displayed to show the playlist. If you switch back to see the cover art, the default image is displayed.
4. The playlist is duplicated, but it doesn't mark which song is playing.

Steps to reproduce:
1. Run app in emulator API Level 28 (or in API Level 29).
2. Play any song an go to _Now playing_.
3. Press button to rotate virtual device.
4. See fail.

Note: If you have a device with Android 9 or Android 10 can reproduce this in your phisical device too.

**Comment by fexofenadine** [comment]
The beta seems to "forget" that shuffle mode is enabled on a currently playing playlist under certain circumstances, such as after a reboot. Can easily be toggled back on but it seems to be a new issue since 3.x

**Comment by tzugen** [comment]
> The beta seems to "forget" that shuffle mode is enabled on a currently playing playlist under certain circumstances, such as after a reboot. Can easily be toggled back on but it seems to be a new issue since 3.x

This is a wontfix unfortunately. The shufflesetting is now specific to the current session and not to a specific playlist

**Comment by fexofenadine** [comment]
Thanks for the reply, that's disappointing 

Could it be made into a configurable item? I'm certain other folks use the app the way I do and will prefer the previous behaviour

**Comment by tzugen** [comment]
> Thanks for the reply, that's disappointing
> 
> Could it be made into a configurable item? I'm certain other folks use the app the way I do and will prefer the previous behaviour

If it is important we could try to store the value inside the PlaybackState object and restore it when resuming.
Best open a new issue for it :)

**Comment by tzugen** [comment]
> ### Strange behavior in device rotation
> When you are playing a song and you rotate the device several strange things happen:
> 
> 1. Playback stops for a moment.
> 2. The song progress bar stops working.
> 3. The disc cover is no longer displayed to show the playlist. If you switch back to see the cover art, the default image is displayed.
> 4. The playlist is duplicated, but it doesn't mark which song is playing.
> 
> Steps to reproduce:
> 
> 1. Run app in emulator API Level 28 (or in API Level 29).
> 2. Play any song an go to _Now playing_.
> 3. Press button to rotate virtual device.
> 4. See fail.
> 
> Note: If you have a device with Android 9 or Android 10 can reproduce this in your phisical device too.

This must be because onResume of the fragment is called and apparently there is some code there is called to réinitialisé the Session.
It shows that there is still work to do with Lifecycle management. I want to move towards using RX more for this. Eg. Have one component broadcast a "stop" or "shutdown" command, and other components like the session listening and acting on this

**Comment by tzugen** [comment]
> Thanks so much for your work on this! I am testing this today, so far all seems to work well. I am on a Pixel 6 Pro (12 (SQ3A.220605.009.B1)).
> 
> Things I have noticed so far:
> 
> * The app doesn't prompt me for media storage permissions, but I can grant it in app info. I haven't noticed any odd behavior yet if it is not granted.
> * The debug logs mention that it can't delete the "partial" file after downloading a track is finished, but the file is not present when I go to look for it, so it seems to delete successfully. Granting storage permissions doesn't stop this log entry from appearing. It's not a serious issue, since usage isn't impacted.
> 
> ```
> 11:10:24.712: W Downloader$downloadChecker Checking Downloads 
> 11:10:24.717: V Downloader Downloader checkDownloadsInternal checking downloads 
> 11:10:24.718: E DownloadFile CLEANING 
> 11:10:24.719: W Storage Failed to delete file /storage/emulated/0/Android/data/org.moire.ultrasonic/files/music/G Jones/Acid Disk 2/05-Flex Acid.partial.mp3 
> 11:10:24.724: I DownloadService DownloadService stopped 
> 11:10:24.729: I Downloader Downloader stopped 
> 11:10:24.730: I DownloadService DownloadService destroyed 
> 11:11:02.211: I MediaPlayerController$onCreate Media3 Event, event type: 3 
> 11:11:02.289: I MediaPlayerController$onCreate Media3 Event, event type: 3 
> ```
> 
> * No album art appears in the media notification, but I'm not sure if this is related to the beta or not - I had the previous app version's notification hidden since it would create the empty notification.
> 
> Let me know if a separate issue should be opened or if you'd like to continue to receive feedback here.

I think the first one is not an issue. We don't need permission if we store the files in the private directory of the app.

For the third can you open a new issue?

Edit: The second I have put here #734

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/753
