### ISSUE TITLE
Crash browsing by folder (unchecking browsing by ID3 label in config)

### ISSUE THREAD

**Issue by Dikakus** [ogarcia/ultrasonic#759]
## Problem description

Browsing by folder, the app suddenly closes. 

### Steps to reproduce

1. Uncheck Browse by ID3 in configuration.
2. Access to Library
3. App closes

### Ultrasonic client

 * **Ultrasonic version**: 3.2.0
 * **Android version**: 10
 * **Device info**: OnePlus 5T

### Server

 * **Server name**: Airsonic
 * **Server version**: 11.0.0-SNAPSHOT.20220418221611
 * **Protocol used**: https (letsencrypt)

## Additional notes

Attached stacktrace:

[ultrasonic-stacktrace.txt](https://github.com/ultrasonic/ultrasonic/files/8938733/ultrasonic-stacktrace.txt)

**Comment by tzugen** [comment]
Thank you, good catch! Will be fixed in the next release.
There is an Album in your collection with an empty artist name. 
You can fix it temporarily by removing that album from the server.
