### ISSUE TITLE
🎉 How to start contributing code 🎍

### ISSUE THREAD

**Issue by tzugen** [ogarcia/ultrasonic#760]
Hi! 
We have collected some information on how you can get setup for making code contributions.
You can find the wiki here and feel free to add more information:
https://github.com/ultrasonic/ultrasonic/blob/develop/CONTRIBUTING.md

**Comment by ogarcia** [comment]
@tzugen Maybe this new wiki page should be merged into [CONTRIBUTING.md](https://github.com/ultrasonic/ultrasonic/blob/develop/CONTRIBUTING.md) which is referenced from [README.md](https://github.com/ultrasonic/ultrasonic/blob/develop/README.md)

**Comment by ogarcia** [comment]
As this is in CONTRIBUTING.md and in GitLab is highlighted on top of repository we can close this issue.
