### ISSUE TITLE
The setting "settings.show_artist_picture" do nothing

### ISSUE THREAD

**Issue by ogarcia** [ogarcia/ultrasonic#769]
With 4.0.0 we have a regression with "settings.show_artist_picture" (Show artist picture in artist list). It should hide the images of the artists but it does nothing.

How it should work:
![artists_list_good](https://user-images.githubusercontent.com/572924/176374310-e95e4adb-15a6-4c22-8284-cf59337114dc.jpg)

How it is working:
![artists_list_bad](https://user-images.githubusercontent.com/572924/176374409-47b514c2-2550-42ef-8e7b-8de187a1128d.jpg)

**Comment by tzugen** [comment]
Which branch are you on? I think it might be a bug just in in the ID3 offline branch

**Comment by tzugen** [comment]
Fixed in the PR #750

**Comment by ogarcia** [comment]
> Which branch are you on? I think it might be a bug just in in the ID3 offline branch

Yes, you are right. I thought it was in the develop branch, but it was in id3-offline. Anyway it's already solved.
